---

base_host_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - apt-transport-https
  - software-properties-common

base_host_apt_proxy_enabled: true
base_host_apt_proxy_url: null

base_host_apt_acquire_retries: 5
base_host_apt_acquire_timeout: 300
base_host_apt_acquire_pipeline_depth: 0

base_host_apt_update_retries: 3
base_host_apt_update_delay: 30

base_host_apt_update_timeout: 1800

base_host_manage_hostname: false
base_host_target_hostname: ""

base_host_apt_unattended_upgrade: false

base_host_split_dns_enabled: false
base_host_split_dns_interface: ""
base_host_split_dns_servers: []
base_host_split_dns_domains: null
