---
container_storage_enabled: true

container_storage_base: /data1

container_storage_docker_root: /data1/docker
container_storage_containerd_root: /data1/containerd

container_storage_docker_mode: "0710"
container_storage_containerd_mode: "0700"

container_storage_graceful_compose_dirs: []

container_storage_compose_stop_timeout: 360

container_storage_migrate: true

container_storage_remove_rollback: false

container_storage_docker_template: null
container_storage_containerd_template: null
