---
flux_unstall_enabled: true

flux_unstall_namespace: observability

flux_unstall_kubectl: null

flux_unstall_flux: null

flux_unstall_resume_timeout: 10m
flux_unstall_retries: 10
flux_unstall_delay: 30
