---
_var_apt_proxy_package: apt-cacher-ng
_var_apt_proxy_service: apt-cacher-ng
_var_apt_proxy_user: apt-cacher-ng
_var_apt_proxy_group: apt-cacher-ng

_var_apt_proxy_override_config_path: /etc/apt-cacher-ng/zzz-rke2lab.conf

_var_apt_proxy_files_dir: "{{ role_path | dirname | dirname }}/files/apt_proxy"
