---
openbao_oidc_enabled: true

openbao_oidc_url: null
openbao_oidc_ca_file: /etc/ssl/certs/ca-certificates.crt

openbao_oidc_issuer: null
openbao_oidc_client_id: openbao

openbao_oidc_discovery_ca_file: null

openbao_oidc_groups_claim: roles

openbao_oidc_redirect_uris:
  - /ui/vault/auth/oidc/oidc/callback
openbao_oidc_cli_redirect_uri: http://localhost:8250/oidc/callback

openbao_oidc_mount: oidc
openbao_oidc_role_name: default
openbao_oidc_admin_role: admin
openbao_oidc_user_role: user
openbao_oidc_admin_policy: sso-admins
openbao_oidc_user_policy: sso-users

openbao_oidc_kv_path: kv

openbao_oidc_token_ttl: 1h
openbao_oidc_token_max_ttl: 8h

openbao_oidc_no_log: true
