---

- name: dns_records | Ensure DNS zones exist
  when:
    - (freeipa_server_enabled | bool)
    - (freeipa_server_dns_zones | length) > 0
    - not ansible_check_mode

  failed_when:
    - _reg_freeipa_server_zone_result is failed
    - >-
      'no modifications to be performed'
      not in (_reg_freeipa_server_zone_result.msg | default(''))
  no_log: "{{ freeipa_server_no_log | default(true) }}"
  register: _reg_freeipa_server_zone_result
  loop: "{{ freeipa_server_dns_zones }}"
  loop_control:
    loop_var: _item_freeipa_server_dns_zone
    label: "{{ _item_freeipa_server_dns_zone['name'] }}"
  community.general.ipa_dnszone:
    ipa_host: "{{ freeipa_server_hostname }}"
    ipa_user: admin
    ipa_pass: "{{ freeipa_server_admin_password }}"
    validate_certs: false
    zone_name: "{{ _item_freeipa_server_dns_zone['name'] }}"
    dynamicupdate: >-
      {{ _item_freeipa_server_dns_zone['dynamic_update'] | default(false) }}
    state: present

- name: dns_records | Ensure service DNS records are published
  when:
    - (freeipa_server_enabled | bool)
    - (freeipa_server_dns_records | length) > 0
    - not ansible_check_mode
  no_log: "{{ freeipa_server_no_log | default(true) }}"
  loop: "{{ freeipa_server_dns_records }}"
  loop_control:
    loop_var: _item_freeipa_server_dns_record
    label: >-
      {{ _item_freeipa_server_dns_record['name'] }}.{{ _item_freeipa_server_dns_record['zone'] | default(freeipa_server_domain) }}
  community.general.ipa_dnsrecord:
    ipa_host: "{{ freeipa_server_hostname }}"
    ipa_user: admin
    ipa_pass: "{{ freeipa_server_admin_password }}"
    validate_certs: false
    zone_name: "{{ _item_freeipa_server_dns_record['zone'] | default(freeipa_server_domain) }}"
    record_name: "{{ _item_freeipa_server_dns_record['name'] }}"
    record_type: "{{ _item_freeipa_server_dns_record['type'] | default('A') }}"
    record_value: "{{ _item_freeipa_server_dns_record['value'] }}"
    state: present
