---

- name: named_options | Render the BIND options customization
  register: _reg_freeipa_server_named_options
  ansible.builtin.template:
    src: "{{ _var_freeipa_server_files_dir }}/named-options-ext.conf.j2"
    dest: "{{ freeipa_server_named_options_path }}"
    owner: root
    group: "{{ freeipa_server_named_config_group }}"
    mode: "0640"

- name: named_options | Restart the domain name service
  when: _reg_freeipa_server_named_options is changed
  changed_when: true
  ansible.builtin.command:
    cmd: >-
      docker exec {{ freeipa_server_container_name }}
      ipactl restart --ignore-service-failures

- name: named_options | Wait for the domain to answer again
  when:
    - _reg_freeipa_server_named_options is changed
    - not ansible_check_mode
  changed_when: false
  register: _reg_freeipa_server_named_ready
  until: (_reg_freeipa_server_named_ready['stdout'] | trim | length) > 0
  retries: 30
  delay: 10
  ansible.builtin.command:
    cmd: >-
      docker exec {{ freeipa_server_container_name }}
      dig +short +time=3 {{ freeipa_server_hostname }} @127.0.0.1
