---
_var_artifact_host_packages:
  - apache2

_var_artifact_host_service: apache2

_var_artifact_host_site_name: artifact-host
_var_artifact_host_site_available: >-
  /etc/apache2/sites-available/artifact-host.conf
_var_artifact_host_site_enabled: >-
  /etc/apache2/sites-enabled/artifact-host.conf

_var_artifact_host_default_site_enabled: >-
  /etc/apache2/sites-enabled/000-default.conf

_var_artifact_host_hardening_conf: >-
  /etc/apache2/conf-available/zzz-artifact-host.conf
_var_artifact_host_hardening_enabled: >-
  /etc/apache2/conf-enabled/zzz-artifact-host.conf

_var_artifact_host_hardening_legacy:
  - /etc/apache2/conf-enabled/artifact-host.conf
  - /etc/apache2/conf-available/artifact-host.conf

_var_artifact_host_modules_enabled:
  - autoindex

_var_artifact_host_modules_disabled:
  - cgi
  - cgid
  - userdir
  - status

_var_artifact_host_files_dir: "{{ role_path | dirname | dirname }}/files/artifact_host"
