---

- name: token | Obtain an admin token
  no_log: "{{ keycloak_clients_no_log | bool }}"
  register: _reg_keycloak_clients_token
  ansible.builtin.uri:
    url: >-
      {{ keycloak_clients_url }}/realms/master/protocol/openid-connect/token
    method: POST
    ca_path: "{{ keycloak_clients_ca_file }}"
    body_format: form-urlencoded
    body:
      grant_type: password
      client_id: admin-cli
      username: "{{ keycloak_clients_admin_user }}"
      password: "{{ keycloak_clients_admin_password }}"
