---
ipa_sub_ca_enabled: true

ipa_sub_ca_ipa_container: freeipa-server
ipa_sub_ca_admin_user: admin

ipa_sub_ca_common_name: null

ipa_sub_ca_profile_id: subCA
ipa_sub_ca_profile_description: >-
  Subordinate CA for the RKE2 cluster, path length 0
ipa_sub_ca_acl_name: subca-k8s
ipa_sub_ca_ca: ipa

ipa_sub_ca_renew_before_days: 90

ipa_sub_ca_domain_ca_file: null

ipa_sub_ca_key_size: 4096

ipa_sub_ca_profile_template: null

ipa_sub_ca_output_dir: >-
  {{ ansible_facts['env']['HOME'] }}/.config/rke2lab/k8s-ca

ipa_sub_ca_no_log: true

ipa_sub_ca_publish_host: ""
ipa_sub_ca_publish_dir: ""
