---
rke2_agent_enabled: true

rke2_agent_config_template: null

rke2_agent_control_data_dir: /data1/rancher/rke2
rke2_agent_control_kubeconfig: /etc/rancher/rke2/rke2.yaml

rke2_agent_ready_retries: 90
rke2_agent_ready_delay: 10
