---
_var_socks5_proxy_package: dante-server
_var_socks5_proxy_service: danted
_var_socks5_proxy_config_path: /etc/danted.conf

_var_socks5_proxy_files_dir: "{{ role_path | dirname | dirname }}/files/socks5_proxy"
