---
ipa_service_cert_enabled: false

ipa_service_cert_names: []

ipa_service_cert_ipa_host: ""
ipa_service_cert_ipa_container: freeipa-server

ipa_service_cert_admin_user: admin
ipa_service_cert_admin_password: ""

ipa_service_cert_dir: null
ipa_service_cert_ca_file: null
ipa_service_cert_key_size: 2048

ipa_service_cert_ca_publish_path: ""

ipa_service_cert_trust_ca: true
ipa_service_cert_trust_ca_path: null

ipa_service_cert_renew_before_days: 30

ipa_service_cert_no_log: true
