---
_var_wireguard_gateway_packages:
  - wireguard
_var_wireguard_gateway_config_path: /etc/wireguard
_var_wireguard_gateway_sysctl_file: /etc/sysctl.d/99-wireguard-gateway.conf
_var_wireguard_gateway_forward_value: >-
  {{ 1 if (wireguard_gateway_ip_forward_enabled | bool) else 0 }}

_var_wireguard_gateway_files_dir: "{{ role_path | dirname | dirname }}/files/wireguard_gateway"
