---
keycloak_realm_admins_enabled: true

keycloak_realm_admins_url: null
keycloak_realm_admins_ca_file: /etc/ssl/certs/ca-certificates.crt

keycloak_realm_admins_admin_user: admin
keycloak_realm_admins_admin_realm: master

keycloak_realm_admins_realm: null

keycloak_realm_admins_allow_master_realm: false

keycloak_realm_admins_group: keycloak-admins

keycloak_realm_admins_client: realm-management

keycloak_realm_admins_roles:
  - realm-admin

keycloak_realm_admins_no_log: true
