---

- name: image_push | Tag the image into the GitLab registry
  community.docker.docker_image_tag:
    name: "{{ _var_rke2_publish_image_local }}"
    repository:
      - "{{ _var_rke2_publish_image_target }}"

- name: image_push | Push the image
  community.docker.docker_image_push:
    name: "{{ _var_rke2_publish_image_target }}"
