---

_var_openbao_oidc_headers:
  X-Vault-Token: "{{ openbao_oidc_root_token }}"

_var_openbao_oidc_discovery_ca: >-
  {{ lookup('file', openbao_oidc_discovery_ca_file, rstrip=false) }}

_var_openbao_oidc_redirect_uris: >-
  {{ (openbao_oidc_redirect_uris | map('regex_replace', '^',
      openbao_oidc_url) | list) + [openbao_oidc_cli_redirect_uri] }}

_var_openbao_oidc_admin_policy: |
  path "{{ openbao_oidc_kv_path }}/data/*" {
    capabilities = ["create", "read", "update", "delete", "list"]
  }
  path "{{ openbao_oidc_kv_path }}/metadata/*" {
    capabilities = ["create", "read", "update", "delete", "list"]
  }
  path "{{ openbao_oidc_kv_path }}/delete/*" {
    capabilities = ["update"]
  }
  path "{{ openbao_oidc_kv_path }}/undelete/*" {
    capabilities = ["update"]
  }

  path "sys/mounts" {
    capabilities = ["read", "list"]
  }
  path "sys/health" {
    capabilities = ["read"]
  }
  path "sys/policies/acl" {
    capabilities = ["list"]
  }
  path "sys/policies/acl/*" {
    capabilities = ["read"]
  }
  path "sys/auth" {
    capabilities = ["read", "list"]
  }
  path "identity/*" {
    capabilities = ["read", "list"]
  }

_var_openbao_oidc_user_policy: |
  path "{{ openbao_oidc_kv_path }}/data/*" {
    capabilities = ["read"]
  }
  path "{{ openbao_oidc_kv_path }}/metadata/*" {
    capabilities = ["read", "list"]
  }
  path "sys/health" {
    capabilities = ["read"]
  }

_var_openbao_oidc_policies:
  - name: "{{ openbao_oidc_admin_policy }}"
    policy: "{{ _var_openbao_oidc_admin_policy }}"
  - name: "{{ openbao_oidc_user_policy }}"
    policy: "{{ _var_openbao_oidc_user_policy }}"

_var_openbao_oidc_groups:
  - name: "{{ openbao_oidc_admin_policy }}"
    alias: "{{ openbao_oidc_admin_role }}"
    policies: ["{{ openbao_oidc_admin_policy }}"]
  - name: "{{ openbao_oidc_user_policy }}"
    alias: "{{ openbao_oidc_user_role }}"
    policies: ["{{ openbao_oidc_user_policy }}"]

_var_openbao_oidc_accessor: >-
  {{ (_reg_openbao_oidc_auth_final['json'][openbao_oidc_mount ~ '/']
      | default({}))['accessor'] | default('') }}
