---
kube_cli_node_enabled: true

kube_cli_node_data_dir: /data1/rancher/rke2

kube_cli_node_link_dir: /usr/local/bin
kube_cli_node_binaries:
  - kubectl
  - crictl
  - ctr

kube_cli_node_kubeconfig: /etc/rancher/rke2/rke2.yaml

kube_cli_node_containerd_sock: unix:///run/k3s/containerd/containerd.sock

kube_cli_node_alias: k
