---

- name: inotify | Ensure the inotify sysctl drop-in is present
  ansible.builtin.template:
    src: "{{ rke2_node_inotify_template }}"
    dest: "{{ _var_rke2_node_inotify_conf_path }}"
    owner: root
    group: root
    mode: "0644"

- name: inotify | Apply the inotify limits to the running kernel
  loop: "{{ _var_rke2_node_inotify_settings | dict2items }}"
  loop_control:
    label: "{{ _item_rke2_node_sysctl['key'] }}"
    loop_var: _item_rke2_node_sysctl
  ansible.posix.sysctl:
    name: "{{ _item_rke2_node_sysctl['key'] }}"
    value: "{{ _item_rke2_node_sysctl['value'] }}"
    sysctl_file: "{{ _var_rke2_node_inotify_conf_path }}"
    sysctl_set: true
    reload: false
    state: present
