---

- name: install | Ensure the installer scratch directory exists
  ansible.builtin.file:
    path: "{{ rke2_node_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: install | Fetch the installer and binary from the package registry
  no_log: true
  loop:
    - install.sh
    - rke2.linux-amd64.tar.gz
    - sha256sum-amd64.txt
  loop_control:
    loop_var: _item_rke2_node_package_file
    label: "{{ _item_rke2_node_package_file }}"
  ansible.builtin.get_url:
    url: >-
      {{ rke2_node_gitlab_url }}/api/v4/projects/{{
      rke2_node_package_project | replace('/', '%2F')
      }}/packages/generic/{{ rke2_node_package_name }}/{{
      rke2_node_version | urlencode }}/{{ _item_rke2_node_package_file }}
    dest: "{{ rke2_node_install_dir }}/{{ _item_rke2_node_package_file }}"
    url_username: "{{ rke2_node_registry_username }}"
    url_password: "{{ rke2_node_registry_password }}"
    force_basic_auth: true
    owner: root
    group: root
    mode: "0700"
    timeout: "{{ rke2_node_download_timeout }}"

- name: install | Check whether this version is already installed
  changed_when: false
  failed_when: false
  register: _reg_rke2_node_installed
  ansible.builtin.command:
    cmd: /usr/local/bin/rke2 --version

- name: install | Run the installer
  when: >-
    _reg_rke2_node_installed['rc'] != 0
    or rke2_node_version.split('+')[0] not in _reg_rke2_node_installed['stdout']
  changed_when: true
  environment:
    INSTALL_RKE2_ARTIFACT_PATH: "{{ rke2_node_install_dir }}"
    INSTALL_RKE2_TYPE: "{{ rke2_node_type }}"
  notify: Restart RKE2
  ansible.builtin.command:
    cmd: sh install.sh
    chdir: "{{ rke2_node_install_dir }}"

- name: install | Ensure the RKE2 data directory exists
  ansible.builtin.file:
    path: "{{ rke2_node_data_dir }}"
    state: directory
    owner: root
    group: root

    mode: "0755"
