---
data_volume_enabled: true

data_volume_device: /dev/sdb

data_volume_filesystem: ext4
data_volume_label: data1

data_volume_mount_path: /data1
data_volume_mount_options: defaults,noatime

data_volume_owner: root
data_volume_group: root
data_volume_mode: "0755"
