---
keycloak_ldap_enabled: true

keycloak_ldap_ipa_host: core01
keycloak_ldap_ipa_container: freeipa-server
keycloak_ldap_base_dn: dc=dev,dc=lo
keycloak_ldap_users_dn: cn=users,cn=accounts,dc=dev,dc=lo

keycloak_ldap_groups_dn: cn=groups,cn=accounts,dc=dev,dc=lo
keycloak_ldap_bind_user: keycloak

keycloak_ldap_configure_keycloak: true

keycloak_ldap_url: null
keycloak_ldap_ca_file: /etc/ssl/certs/ca-certificates.crt

keycloak_ldap_realm: null

keycloak_ldap_allow_master_realm: false

keycloak_ldap_admin_user: admin

keycloak_ldap_provider_name: freeipa

keycloak_ldap_connection_url: null

keycloak_ldap_first_name_mapper: first name
keycloak_ldap_first_name_attribute: givenName

keycloak_ldap_user_search_filter: "(!(nsAccountLock=TRUE))"

keycloak_ldap_groups_filter: null

keycloak_ldap_email_verified_mapper_enabled: true
keycloak_ldap_email_verified_mapper_name: email verified

keycloak_ldap_group_mapper_enabled: true
keycloak_ldap_group_mapper_name: freeipa-groups

keycloak_ldap_group_sync: true

keycloak_ldap_user_sync: true

keycloak_ldap_clear_user_cache: true

keycloak_ldap_manage_sysaccount: true

keycloak_ldap_no_log: true
