---
keycloak_realm_enabled: true

keycloak_realm_url: null
keycloak_realm_ca_file: /etc/ssl/certs/ca-certificates.crt

keycloak_realm_admin_user: admin

keycloak_realm_name: null
keycloak_realm_display_name: null

keycloak_realm_access_token_lifespan: 300
keycloak_realm_sso_session_idle_timeout: 3600
keycloak_realm_sso_session_max_lifespan: 36000

keycloak_realm_brute_force_protected: true
keycloak_realm_failure_factor: 10

keycloak_realm_no_log: true
