---

_var_ipa_sub_ca_key: "{{ ipa_sub_ca_output_dir }}/{{ ipa_sub_ca_common_name }}.key"
_var_ipa_sub_ca_csr: "{{ ipa_sub_ca_output_dir }}/{{ ipa_sub_ca_common_name }}.csr"
_var_ipa_sub_ca_crt: "{{ ipa_sub_ca_output_dir }}/{{ ipa_sub_ca_common_name }}.crt"

_var_ipa_sub_ca_remote_profile: "/tmp/{{ ipa_sub_ca_profile_id }}.cfg"
_var_ipa_sub_ca_remote_csr: "/tmp/{{ ipa_sub_ca_common_name }}.csr"
_var_ipa_sub_ca_remote_crt: "/tmp/{{ ipa_sub_ca_common_name }}.pem"
