---
all:
  children:
    controller:
      hosts:
        controller01:
          ansible_connection: local
          ansible_host: 127.0.0.1
          ansible_user: claw
    repo:
      hosts:
        repo01:
          ansible_host: 192.168.1.20
          ansible_user: root
    core:
      hosts:
        core01:
          ansible_host: 192.168.2.4
    kubecp:
      hosts:
        kubecp01:
          ansible_host: 192.168.2.21
        kubecp02:
          ansible_host: 192.168.2.22
        kubecp03:
          ansible_host: 192.168.2.23
    kubewk:
      hosts:
        kubewk01:
          ansible_host: 192.168.2.31
        kubewk02:
          ansible_host: 192.168.2.32
        kubewk03:
          ansible_host: 192.168.2.33
