---
openbao_secrets_enabled: true

openbao_secrets_url: null

openbao_secrets_ca_file: /etc/ssl/certs/ca-certificates.crt

openbao_secrets_kv_path: kv

openbao_secrets_grafana_admin_user: admin

openbao_secrets_garage_s3_access_key: ""
openbao_secrets_garage_s3_secret_key: ""

openbao_secrets_no_log: true
