---
keycloak_break_glass_enabled: true

keycloak_break_glass_url: null
keycloak_break_glass_ca_file: /etc/ssl/certs/ca-certificates.crt

keycloak_break_glass_admin_user: admin

keycloak_break_glass_realm: master

keycloak_break_glass_admin_role: admin

keycloak_break_glass_remove_federation: true

keycloak_break_glass_allowed_federation: []

keycloak_break_glass_no_log: true
