---

_var_artifact_stage_tag_suffix: .tag

_var_artifact_stage_digest_suffix: .digest

_var_artifact_stage_checksum_suffix: .sha256

_var_artifact_stage_published_suffix: .published

_var_artifact_stage_wanted: >-
  {{ _var_artifact_stage_local
     | rejectattr('name', 'in',
                  artifact_stage_published_names
                  + _artifact_stage_marked_names) | list }}

_var_artifact_stage_local: >-
  {{ artifact_stage_manifest
     | rejectattr('type', 'equalto', 'mirror') | list }}

_var_artifact_stage_files: >-
  {{ _var_artifact_stage_wanted | selectattr('type', 'equalto', 'file') | list }}
_var_artifact_stage_images: >-
  {{ _var_artifact_stage_wanted | selectattr('type', 'equalto', 'image') | list }}
