---
- name: Update the system trust store
  changed_when: true
  ansible.builtin.command:
    cmd: update-ca-certificates

- name: Restart RKE2
  when: _rke2_service_running | default(false) | bool
  ansible.builtin.systemd_service:
    name: "rke2-{{ rke2_node_type }}"
    state: restarted
