---
ipa_sso_groups_enabled: true

ipa_sso_groups_ipa_host: null
ipa_sso_groups_ipa_container: null
ipa_sso_groups_admin_user: admin

ipa_sso_groups_applications: []

ipa_sso_groups_admin_only_applications: []

ipa_sso_groups_admin_suffix: admins
ipa_sso_groups_user_suffix: users

ipa_sso_groups_no_log: true
