---
keycloak_clients_enabled: true

keycloak_clients_url: null
keycloak_clients_ca_file: /etc/ssl/certs/ca-certificates.crt

keycloak_clients_admin_user: admin

keycloak_clients_realm: null

keycloak_clients_applications: []

keycloak_clients_admin_suffix: admins
keycloak_clients_user_suffix: users
keycloak_clients_admin_role: admin
keycloak_clients_user_role: user

keycloak_clients_roles_claim: roles

keycloak_clients_no_log: true
