---

_var_ipa_service_cert_packages:
  - openssl

_var_ipa_service_cert_crt: >-
  {{ ipa_service_cert_dir }}/{{ _item_ipa_service_cert_entry['name'] }}.crt
_var_ipa_service_cert_key: >-
  {{ ipa_service_cert_dir }}/{{ _item_ipa_service_cert_entry['name'] }}.key
_var_ipa_service_cert_csr: >-
  {{ ipa_service_cert_dir }}/{{ _item_ipa_service_cert_entry['name'] }}.csr
_var_ipa_service_cert_principal: >-
  {{ _item_ipa_service_cert_entry['service'] | default('HTTP', true) }}/{{
  _item_ipa_service_cert_entry['name'] }}

_var_ipa_service_cert_remote_csr: >-
  /tmp/{{ _item_ipa_service_cert_entry['name'] }}.csr
_var_ipa_service_cert_remote_crt: >-
  /tmp/{{ _item_ipa_service_cert_entry['name'] }}.pem
