---
wireguard_gateway_enabled: false
wireguard_gateway_interface: wg0
wireguard_gateway_private_key: ""
wireguard_gateway_peer_public_key: ""
wireguard_gateway_ip_forward_enabled: true
wireguard_gateway_template: null
