---

_var_openbao_init_keys: >-
  {{ (_reg_openbao_init_result['stdout'] | default('{}') | from_json)
     ['unseal_keys_b64'] | default([]) }}
_var_openbao_init_root: >-
  {{ (_reg_openbao_init_result['stdout'] | default('{}') | from_json)
     ['root_token'] | default('') }}
