---
split_dns_enabled: true

split_dns_forward_zones: []

split_dns_manage_resolver: true

split_dns_verify_zones: true

split_dns_packages:
  - dnsmasq

  - bind9-dnsutils

split_dns_config_template: null
split_dns_resolver_template: null
