---
- name: config | Render the RKE2 server configuration
  no_log: true
  notify: Restart the RKE2 server
  ansible.builtin.template:
    src: "{{ rke2_server_config_template }}"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0600"
