---

- name: kube_vip | Ensure the auto-deploy manifest directory exists
  ansible.builtin.file:
    path: "{{ rke2_server_data_dir }}/server/manifests"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: kube_vip | Render the kube-vip RBAC and DaemonSet
  ansible.builtin.template:
    src: "{{ rke2_server_kube_vip_template }}"
    dest: "{{ rke2_server_data_dir }}/server/manifests/kube-vip.yaml"
    owner: root
    group: root
    mode: "0600"
