---

- name: kubeconfig | Read the cluster kubeconfig
  no_log: true
  register: _reg_rke2_server_kubeconfig
  ansible.builtin.slurp:
    src: /etc/rancher/rke2/rke2.yaml

- name: kubeconfig | Ensure the destination directory exists
  become: false
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ rke2_server_kubeconfig_dest | dirname }}"
    state: directory
    owner: "{{ _var_rke2_server_kubeconfig_owner }}"
    group: "{{ _var_rke2_server_kubeconfig_owner }}"
    mode: "0700"

- name: kubeconfig | Write the controller kubeconfig
  become: false
  delegate_to: localhost
  no_log: true
  ansible.builtin.copy:
    content: >-
      {{ _reg_rke2_server_kubeconfig['content'] | b64decode
         | regex_replace('https://127\.0\.0\.1:' ~ rke2_server_api_port,
                         'https://' ~ rke2_server_api_name ~ ':'
                         ~ rke2_server_api_port) }}
    dest: "{{ rke2_server_kubeconfig_dest }}"
    owner: "{{ _var_rke2_server_kubeconfig_owner }}"
    group: "{{ _var_rke2_server_kubeconfig_owner }}"
    mode: "0600"

- name: kubeconfig | Prove the controller can reach the cluster
  changed_when: false
  become: false
  delegate_to: localhost
  ansible.builtin.uri:
    url: >-
      https://{{ rke2_server_api_name }}:{{ rke2_server_api_port }}/readyz
    validate_certs: false
    status_code: [200, 401, 403]
