---

- name: Establish the controller's trust state
  hosts: controller
  gather_facts: true
  become: false
  tasks:
    - name: controller | Include the controller trust role
      tags:
        - controller_trust
      vars:
        controller_trust_ca_path: "{{ inventory_controller_trust_ca_path }}"
        controller_trust_ca_url: "{{ inventory_controller_trust_ca_url }}"
        controller_trust_verify_url: "{{ inventory_controller_trust_verify_url }}"

        controller_trust_hosts: >-
          {{ groups['all'] | difference(groups['controller'])
             | map('extract', hostvars, 'ansible_host') | list }}
      ansible.builtin.include_role:
        name: controller_trust
        apply:
          tags:
            - controller_trust

- name: Set up the controller to operate the cluster
  hosts: controller
  gather_facts: true
  become: false
  tasks:
    - name: controller | Include the controller CLI role
      tags:
        - kube_cli
      vars:

        kube_cli_controller_bin_dir: >-
          {{ inventory_kube_cli_controller_bin_dir }}
        kube_cli_controller_config_dir: >-
          {{ inventory_kube_cli_controller_config_dir }}
        kube_cli_controller_flux_url: >-
          {{ inventory_kube_cli_controller_flux_url }}
        kube_cli_controller_flux_version: >-
          {{ inventory_kube_cli_controller_flux_version }}
        kube_cli_controller_k9s_url: "{{ inventory_kube_cli_controller_k9s_url }}"
        kube_cli_controller_k9s_version: >-
          {{ inventory_kube_cli_controller_k9s_version }}
        kube_cli_controller_kubectl_source_host: >-
          {{ inventory_kubewk_control_host }}
        kube_cli_controller_kubectl_source_path: >-
          {{ hostvars[inventory_kubewk_control_host]['inventory_rke2_node_data_dir'] }}/bin/kubectl
        kube_cli_controller_kubeseal_url: >-
          {{ inventory_kube_cli_controller_kubeseal_url }}
        kube_cli_controller_kubeseal_version: >-
          {{ inventory_kube_cli_controller_kubeseal_version }}
        kube_cli_controller_kubeconfig: >-
          {{ inventory_kube_cli_controller_kubeconfig }}
        kube_cli_controller_shell_template: >-
          {{ inventory_kube_cli_controller_shell_template }}
        kube_cli_controller_kubectl_version: >-
          {{ hostvars[inventory_kubewk_control_host]['inventory_rke2_node_version']
             | regex_replace('\+.*$', '') }}
      ansible.builtin.include_role:
        name: kube_cli_controller
        apply:
          tags:
            - kube_cli
