---
artifact_host_enabled: true

artifact_host_document_root: /data1/artifacts

artifact_host_directories:
  - certs
  - freeipa
  - gitlab
  - runtime
  - rke2
  - charts

artifact_host_listen_port: 80
artifact_host_server_name: null

artifact_host_allowed_networks: null

artifact_host_directory_index_enabled: true

artifact_host_owner: root
artifact_host_group: root
artifact_host_directory_mode: "0755"
artifact_host_file_mode: "0644"
