---
artifact_host_enabled: true

artifact_host_document_root: /data1/artifacts

artifact_host_directories:
  - certs
  - freeipa
  - gitlab
  - runtime
  - rke2
  - charts

artifact_host_owner: root
artifact_host_group: root
artifact_host_directory_mode: "0755"
artifact_host_file_mode: "0644"

artifact_host_hardening_template: null
artifact_host_vhost_template: null
