---
kube_cli_controller_enabled: true

kube_cli_controller_bin_dir: "{{ ansible_facts['env']['HOME'] }}/.local/bin"
kube_cli_controller_config_dir: >-
  {{ ansible_facts['env']['HOME'] }}/.config/rke2lab

kube_cli_controller_shell_rc_files:
  - "{{ ansible_facts['env']['HOME'] }}/.bashrc"
  - "{{ ansible_facts['env']['HOME'] }}/.profile"

kube_cli_controller_kubeconfig: >-
  {{ ansible_facts['env']['HOME'] }}/.kube/dev-lo.config

kube_cli_controller_kubectl_enabled: true
kube_cli_controller_kubectl_source_host: kubecp01
kube_cli_controller_kubectl_source_path: /data1/rancher/rke2/bin/kubectl

kube_cli_controller_kubectl_version: 1.36.3

kube_cli_controller_k9s_enabled: true
kube_cli_controller_k9s_version: null
kube_cli_controller_k9s_url: null

kube_cli_controller_shell_enabled: true
kube_cli_controller_alias: k

kube_cli_controller_flux_enabled: true
kube_cli_controller_flux_version: null
kube_cli_controller_flux_url: null

kube_cli_controller_kubeseal_enabled: true
kube_cli_controller_kubeseal_version: null
kube_cli_controller_kubeseal_url: null
