---

- name: interface | Ensure the WireGuard configuration directory exists
  ansible.builtin.file:
    path: "{{ _var_controller_tunnel_config_path }}"
    state: directory
    mode: "0700"

- name: interface | Ensure the WireGuard interface configuration is rendered
  notify:
    - Restart controller WireGuard
  ansible.builtin.template:
    src: "{{ _var_controller_tunnel_files_dir }}/wg_controller.conf.j2"
    dest: "{{ _var_controller_tunnel_config_file }}"
    mode: "0600"

- name: interface | Ensure the WireGuard interface is enabled and started
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: "{{ _var_controller_tunnel_service }}"
    enabled: true
    state: started

- name: interface | Apply any pending interface restart
  ansible.builtin.meta: flush_handlers
