---
_var_keycloak_realm_admins_headers:
  Authorization: >-
    Bearer {{ _reg_keycloak_realm_admins_token['json']['access_token']
              | default('') }}

_var_keycloak_realm_admins_admin_api: >-
  {{ keycloak_realm_admins_url }}/admin/realms/{{
  keycloak_realm_admins_realm }}

_var_keycloak_realm_admins_group_id: >-
  {{ (_reg_keycloak_realm_admins_groups['json'] | default([])
      | selectattr('name', 'equalto', keycloak_realm_admins_group)
      | list | first | default({}))['id'] | default('') }}

_var_keycloak_realm_admins_client_id: >-
  {{ (_reg_keycloak_realm_admins_client['json'] | default([])
      | selectattr('clientId', 'equalto', keycloak_realm_admins_client)
      | list | first | default({}))['id'] | default('') }}

_var_keycloak_realm_admins_missing: >-
  {{ _reg_keycloak_realm_admins_roles['json'] | default([])
     | selectattr('name', 'in', keycloak_realm_admins_roles)
     | rejectattr('name', 'in',
                  _reg_keycloak_realm_admins_granted['json'] | default([])
                  | map(attribute='name') | list)
     | list }}
