---
longhorn_node_enabled: true

longhorn_node_packages:
  - open-iscsi
  - nfs-common
  - cryptsetup

longhorn_node_iscsi_service: iscsid

longhorn_node_data_path: /var/lib/longhorn

longhorn_node_root_device: /dev/sda

longhorn_node_multipath_blacklist: true
longhorn_node_multipath_conf: /etc/multipath/conf.d/longhorn.conf

longhorn_node_blacklist_template: null
