---
inventory_phase1_environment_name: dev_lo

inventory_kubewk_control_host: kubecp01

inventory_cluster_services_ipa_host: core01

inventory_rke2_node_registry_mirrors:

  - upstream: docker.io
    pattern: "^(.*)"
    replacement: rke2/images/$1
  - upstream: registry-1.docker.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: ghcr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: gcr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: quay.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: registry.k8s.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: mcr.microsoft.com
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: public.ecr.aws
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: icr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: cgr.dev
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: nvcr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: registry.redhat.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: registry.access.redhat.com
    pattern: "^(.*)"
    replacement: rke2/images/$1
