---

controller_tunnel_enabled: true

controller_tunnel_configure_enabled: true
controller_tunnel_validate_enabled: true

controller_tunnel_interface: wg0

controller_tunnel_private_key: ""

controller_tunnel_peer_private_key: ""

controller_tunnel_peer_public_key: ""

controller_tunnel_wg_template: null

controller_tunnel_validate_address: null
controller_tunnel_validate_port: 22
controller_tunnel_validate_timeout: 30
