---
controller_trust_enabled: true

controller_trust_ca_url: null
controller_trust_ca_path: null
controller_trust_update_command: update-ca-certificates

controller_trust_verify_url: null

controller_trust_system_bundle: /etc/ssl/certs/ca-certificates.crt

controller_trust_hosts: []
controller_trust_known_hosts: >-
  {{ ansible_facts['env']['HOME'] }}/.ssh/known_hosts
controller_trust_keyscan: ssh-keyscan -t ed25519 -T 5
