---

_var_ipa_sso_groups_all: >-
  {{ (ipa_sso_groups_applications
      | map(attribute='name')
      | product([ipa_sso_groups_admin_suffix, ipa_sso_groups_user_suffix])
      | map('join', '-') | list)
     + (ipa_sso_groups_admin_only_applications
        | map(attribute='name')
        | product([ipa_sso_groups_admin_suffix])
        | map('join', '-') | list) }}
