---

_var_controller_tunnel_packages:
  - wireguard-tools

_var_controller_tunnel_config_path: /etc/wireguard

_var_controller_tunnel_files_dir: >-
  {{ role_path | dirname | dirname }}/files/controller_tunnel

_var_controller_tunnel_config_file: >-
  {{ _var_controller_tunnel_config_path }}/{{ controller_tunnel_interface }}.conf

_var_controller_tunnel_service: >-
  wg-quick@{{ controller_tunnel_interface }}
