---
openbao_config_enabled: true

openbao_config_url: null

openbao_config_ca_file: /etc/ssl/certs/ca-certificates.crt

openbao_config_kubernetes_host: https://kubernetes.default.svc:443

openbao_config_kubectl: >-
  {{ ansible_facts['env']['HOME'] }}/.local/bin/kubectl
  --kubeconfig {{ ansible_facts['env']['HOME'] }}/.kube/dev-lo.config

openbao_config_kv_path: kv

openbao_config_namespace: external-secrets
openbao_config_service_account: external-secrets
openbao_config_role_name: external-secrets
openbao_config_policy_name: external-secrets-read
openbao_config_token_ttl: 24h

openbao_config_no_log: true
