---
openbao_init_enabled: true

openbao_init_namespace: openbao
openbao_init_pod: openbao-0

openbao_init_key_shares: 5
openbao_init_key_threshold: 3

openbao_init_env_file: >-
  {{ ansible_facts['env']['HOME'] }}/.config/rke2lab/env.sh

openbao_init_kubectl: >-
  {{ ansible_facts['env']['HOME'] }}/.local/bin/kubectl
  --kubeconfig {{ ansible_facts['env']['HOME'] }}/.kube/dev-lo.config

openbao_init_no_log: true
