---
_var_time_sync_config_path: /etc/chrony/chrony.conf
_var_time_sync_service_name: chrony

_var_time_sync_timesyncd_unit: /usr/lib/systemd/system/systemd-timesyncd.service

_var_time_sync_files_dir: "{{ role_path | dirname | dirname }}/files/time_sync"
