---

ansible_user: "{{ lookup('env', 'VM_USERNAME') | default('root', true) }}"
ansible_password: "{{ lookup('env', 'VM_USER_PASSWORD') }}"
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

inventory_base_host_manage_hostname: true
inventory_base_host_target_hostname: "{{ inventory_hostname }}.dev.lo"

inventory_base_host_apt_proxy_enabled: true
inventory_base_host_apt_proxy_url: http://192.168.2.99:3142

inventory_base_host_split_dns_enabled: false

inventory_time_sync_enabled: true
inventory_time_sync_source_directive: server
inventory_time_sync_sources:
  - 192.168.2.4 iburst

inventory_data_volume_enabled: true
inventory_data_volume_device: /dev/sdb
inventory_data_volume_filesystem: ext4
inventory_data_volume_label: data1
inventory_data_volume_mount_path: /data1

inventory_rke2_node_enabled: true
inventory_rke2_node_type: server
inventory_rke2_node_version: 1.36.3+rke2r1
inventory_rke2_node_data_dir: /data1/rancher/rke2
inventory_rke2_node_ca_url: http://192.168.2.99/certs/dev.lo-ca.crt
inventory_rke2_node_gitlab_url: https://gitlab.dev.lo
inventory_rke2_node_registry_host: registry.gitlab.dev.lo
inventory_rke2_node_package_project: rke2/packages

inventory_kubecp_bootstrap_host: kubecp01

inventory_rke2_server_enabled: true

inventory_rke2_server_token: "{{ lookup('env', 'RKE2_TOKEN') }}"
inventory_rke2_server_node_ip: "{{ ansible_host }}"
inventory_rke2_server_api_address: 192.168.2.20
inventory_rke2_server_api_name: kube.dev.lo

inventory_rke2_server_api_port: 6443
inventory_rke2_server_supervisor_port: 9345
inventory_rke2_server_data_dir: "{{ inventory_rke2_node_data_dir }}"

inventory_rke2_server_tls_san:
  - kube.dev.lo
  - 192.168.2.20
  - kubecp01.dev.lo
  - kubecp02.dev.lo
  - kubecp03.dev.lo
  - 192.168.2.21
  - 192.168.2.22
  - 192.168.2.23

inventory_rke2_server_cni: cilium

inventory_rke2_server_expose_metrics: true

inventory_rke2_server_disable: []
inventory_rke2_server_ingress_controller:
  - traefik

inventory_rke2_server_node_taints:
  - CriticalAddonsOnly=true:NoExecute

inventory_rke2_server_kube_vip_enabled: true
inventory_rke2_server_kube_vip_image: ghcr.io/kube-vip/kube-vip:v1.2.3
inventory_rke2_server_kube_vip_interface: eth0

inventory_base_host_split_dns_domains:
  - dev.lo

inventory_rke2_node_ca_system_path: /usr/local/share/ca-certificates/dev.lo.crt
inventory_rke2_node_ca_rke2_path: /etc/rancher/rke2/dev.lo-ca.crt

inventory_rke2_server_ingress_address: 192.168.2.41
