---

_var_container_storage_base_re: "^{{ container_storage_base }}/"
_var_container_storage_mountpoints: >-
  {{ ansible_facts['mounts'] | map(attribute='mount') | list }}

_var_container_storage_docker_config: /etc/docker/daemon.json
_var_container_storage_containerd_config: /etc/containerd/config.toml

_var_container_storage_units:
  - docker.socket
  - docker.service
  - containerd.service

_var_container_storage_moves:
  - name: docker
    src: /var/lib/docker
    dest: "{{ container_storage_docker_root }}"
    mode: "{{ container_storage_docker_mode }}"
  - name: containerd
    src: /var/lib/containerd
    dest: "{{ container_storage_containerd_root }}"
    mode: "{{ container_storage_containerd_mode }}"

_var_container_storage_files_dir: "{{ role_path | dirname | dirname }}/files/container_storage"
