---
rke2_node_enabled: true

rke2_node_type: server

rke2_node_version: 1.36.3+rke2r1

rke2_node_data_dir: /data1/rancher/rke2

rke2_node_inotify_max_user_instances: 8192
rke2_node_inotify_max_user_watches: 524288

rke2_node_install_dir: /data1/rke2-install

rke2_node_ca_url: null
rke2_node_ca_system_path: null
rke2_node_ca_rke2_path: null

rke2_node_gitlab_url: null

rke2_node_registries_template: null
rke2_node_inotify_template: null

rke2_node_package_project: rke2/packages
rke2_node_package_name: rke2

rke2_node_registry_mirrors:

  - upstream: docker.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: registry-1.docker.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: ghcr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: gcr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: quay.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: registry.k8s.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: mcr.microsoft.com
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: registry.redhat.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: registry.access.redhat.com
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: cgr.dev
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: public.ecr.aws
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: icr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

  - upstream: nvcr.io
    pattern: "^(.*)"
    replacement: rke2/images/$1

rke2_node_download_timeout: 600
