---
argument_specs:
  main:
    short_description: SOCKS5 proxy role inputs.
    options:
      socks5_proxy_enabled:
        type: bool
        required: false
      socks5_proxy_template:
        description: Path to the danted.conf template, under the repo files tree.
        type: str
        required: false
