---
galaxy_info:
  role_name: socks5_proxy
  author: devops
  description: SOCKS5 proxy setup using danted.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
